In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("./Datasets/Task_data.csv")
df.head()

user_id      age     salary department   join_date       city  \
0  user_0       -5     ₹50000         HR  2020/12/01      DELHI   
1   U1001       30      45000    Finance  15/02/2021      Delhi   
2   U1002       30      25000         HR         NaN      Delhi   
3     NaN  unknown        NaN         HR     invalid  Hyderabad   
4     NaN      NaN  120000.75         IT         NaN      DELHI   

  performance_score experience_years is_active  
0                 3             five      True  
1                 3                1       yes  
2         excellent               10     False  
3         excellent                5       yes  
4               NaN               -1     False

In [52]:
df.shape , df.size

((1000, 9), 9000)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   user_id            490 non-null    object
 1   age                886 non-null    object
 2   salary             689 non-null    object
 3   department         859 non-null    object
 4   join_date          781 non-null    object
 5   city               851 non-null    object
 6   performance_score  899 non-null    object
 7   experience_years   873 non-null    object
 8   is_active          800 non-null    object
dtypes: object(9)
memory usage: 70.4+ KB


In [54]:
df.isna().sum()

user_id              510
age                  114
salary               311
department           141
join_date            219
city                 149
performance_score    101
experience_years     127
is_active            200
dtype: int64

In [55]:
df.columns

Index(['user_id', 'age', 'salary', 'department', 'join_date', 'city',
       'performance_score', 'experience_years', 'is_active'],
      dtype='object')

In [56]:
df.dtypes

user_id              object
age                  object
salary               object
department           object
join_date            object
city                 object
performance_score    object
experience_years     object
is_active            object
dtype: object

In [57]:
# 2 
( df.isna().sum() / 1000 ) * 100

user_id              51.0
age                  11.4
salary               31.1
department           14.1
join_date            21.9
city                 14.9
performance_score    10.1
experience_years     12.7
is_active            20.0
dtype: float64

In [58]:

# 3 
for col in df.columns:
    if  not col == "user_id" :
        print(col)
        print(df[col].unique())


age
['-5' '30' 'unknown' nan '45' '200' '18' '60' '25']
salary
['₹50000' '45000' '25000' nan '120000.75' '78000']
department
['HR' 'Finance' 'IT' nan 'Sales' 'it ']
join_date
['2020/12/01' '15/02/2021' nan 'invalid' '2022-01-15']
city
['DELHI' 'Delhi' 'Hyderabad' nan 'mumbai' 'Bangalore' 'Mumbai']
performance_score
['3' 'excellent' nan '5' 'poor' '4' '1' '2']
experience_years
['five' '1' '10' '5' '-1' '0' nan '3']
is_active
['True' 'yes' 'False' 'no' nan]


In [59]:
# 4 
df['user_id'].replace("", np.nan , inplace = True)
df.user_id = df.user_id.str.upper()

In [60]:
# 5 
df.replace('unknown' , np.nan , inplace=True)

In [61]:
df['age'] = df['age'].astype("float64")

In [62]:
df[(df['age'] > 100 ) | (df['age']<0)] = np.nan 

In [63]:
df['age'].unique()

array([nan, 30., 45., 18., 60., 25.])

In [64]:
# 6
df['salary'].replace('₹50000',50000 ,inplace= True)

In [65]:
df['salary'] = df['salary'].astype("float64")

In [66]:
df['salary'].unique()

array([      nan,  45000.  ,  25000.  , 120000.75,  78000.  ,  50000.  ])

In [67]:
# 7
df['join_date'].unique()

array([nan, '15/02/2021', 'invalid', '2022-01-15', '2020/12/01'],
      dtype=object)

In [68]:
df['join_date'].replace('invalid' , np.nan , inplace=True)

In [69]:
df['join_date'] = pd.to_datetime(df['join_date'] , format="mixed")

In [70]:
df['join_date'].unique()

<DatetimeArray>
['NaT', '2021-02-15 00:00:00', '2022-01-15 00:00:00', '2020-12-01 00:00:00']
Length: 4, dtype: datetime64[ns]

In [71]:
# 8
df['joining_year'] = df['join_date'].dt.year

In [72]:
df.joining_year.unique()

array([  nan, 2021., 2022., 2020.])

In [73]:
#10
df['department'] = df['department'].str.strip().str.upper()
        

In [74]:
df.city = df.city.str.title()

In [75]:
df.city.unique()

array([nan, 'Delhi', 'Hyderabad', 'Mumbai', 'Bangalore'], dtype=object)

In [76]:
# 11
mapvalue = {
    "excellent" : 5 ,
    "4":4,
    "3" : 3,
    "2" : 2,
    "poor": 1 ,
}
df.performance_score = df.performance_score.map(mapvalue)


In [77]:
df.performance_score.unique()

array([nan,  3.,  5.,  4.,  2.,  1.])

In [78]:
#12
df.experience_years.replace('five' , 5 , inplace=True)

In [79]:
df.experience_years = df.experience_years.astype("float64")

In [80]:
df.experience_years.unique()

array([nan,  1., 10.,  5., -1.,  0.,  3.])

In [86]:
df.loc[df['experience_years'] < 0 , "experience_years"] = np.nan

In [87]:
df.experience_years.unique()

array([nan,  1., 10.,  5.,  0.,  3.])

In [90]:
# 13
df.is_active.replace({"yes":True, "no": False} , inplace = True)

In [92]:
df.is_active = df.is_active.astype("bool")

In [96]:
# 14 
df['user_id'].duplicated()

0      False
1      False
2      False
3       True
4       True
       ...  
995     True
996    False
997    False
998     True
999     True
Name: user_id, Length: 1000, dtype: bool

In [98]:
df['user_id'] = df['user_id'].drop_duplicates()

In [102]:
# 15
final_df = df.dropna()

In [103]:
final_df.head()

user_id   age   salary department  join_date    city  performance_score  \
1     U1001  30.0  45000.0    FINANCE 2021-02-15   Delhi                3.0   
16    U1016  25.0  45000.0    FINANCE 2020-12-01   Delhi                4.0   
29  USER_29  25.0  25000.0         HR 2020-12-01   Delhi                1.0   
61  USER_61  25.0  50000.0    FINANCE 2020-12-01  Mumbai                3.0   
94  USER_94  18.0  50000.0         IT 2022-01-15  Mumbai                4.0   

    experience_years  is_active  joining_year  
1                1.0       True        2021.0  
16               1.0       True        2020.0  
29               3.0       True        2020.0  
61              10.0       True        2020.0  
94               3.0       True        2022.0

In [ ]:
final_df.